### ISSUE TITLE
Front End Lock

### ISSUE THREAD

**Issue by colatf5** [s-archer/quick-demos-arch#1]
RE: quick-demos-arch/auto-workshop/vdi-build/main-post-vdi-deploy.yaml

Hey mate. I see there's a section in the playbook specifically to avoid a "front end lock issue". FYI I still get that. No biggie for me, I can update ansible from the CLI.

TASK [INSTALL LATEST ANSIBLE] ***********************************************************************
Monday 14 October 2019  09:48:51 +0100 (0:00:25.226)       0:02:09.415 ******** 
 [WARNING]: Updating cache and auto-installing missing dependency: python-apt

fatal: [34.244.90.20]: FAILED! => {"changed": false, "cmd": "apt-get install --no-install-recommends python-apt -y -q", "msg": "E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)\nE: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?", "rc": 100, "stderr": "E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)\nE: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?\n", "stderr_lines": ["E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)", "E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?"], "stdout": "", "stdout_lines": []}

**Comment by s-archer** [comment]
It's fixed now. 👍
